version: 2
references:
  cache_key_dependencies: &cache_key_dependencies
    key: deps-cache
  cache_key_build: &cache_key_build
    key: build-cache
  restore_cache_dependencies: &restore_cache_dependencies
    restore_cache:
      <<: *cache_key_dependencies
  restore_cache_build: &restore_cache_build
    restore_cache:
      <<: *cache_key_build
  save_cache_dependencies: &save_cache_dependencies
    save_cache:
      <<: *cache_key_dependencies
      paths:
        - ~/.m2
        - ~/.gradle
  save_cache_build: &save_cache_build
    save_cache:
      <<: *cache_key_build
      paths:
        - ~/workspace/buildAgent
  workspace: &workspace ~/workspace
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      TERM: dumb
      JVM_OPTS: "-Xmx3200m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx3200m"'
      BUILD_AGENT_DIR: '~/workspace/buildAgent'
jobs:
  build:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache_dependencies
      - *restore_cache_build
      - run: wget --quiet ${SERVER_HOST}/update/buildAgent.zip
      - run: mkdir -p -v $BUILD_AGENT_DIR
      - run: unzip -o buildAgent.zip -d $BUILD_AGENT_DIR
      - run: rm buildAgent.zip
      - run: cat ${HOME}/workspace/buildAgent.properties > $BUILD_AGENT_DIR/conf/buildAgent.properties
      - run: echo 'authorizationToken=${TEAMCITY_AGENT_AUTH_TOKEN}' >> $BUILD_AGENT_DIR/conf/buildAgent.properties
      - run: bash $BUILD_AGENT_DIR/bin/agent.sh start
      - run: while tail $BUILD_AGENT_DIR/logs/teamcity-agent.log -f ; do sleep 0 ; done
      - *save_cache_dependencies
      - *save_cache_build
workflows:
  version: 2
  workflow:
    jobs:
      - build
